<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Category;
use Carbon\Carbon;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('categories')->insert([
            [
                'name' => 'Trang chủ',
                'slug' => 'trang-chu',
                'description' => 'Trang chủ',
                'is_visible' => true,
                'seo_title' => 'trang-chu',
                'seo_description' => 'trang-chu',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Giới thiệu',
                'slug' => 'gioi-thieu',
                'description' => 'Giới thiệu',
                'is_visible' => true,
                'seo_title' => 'gioi-thieu',
                'seo_description' => 'gioi-thieu',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Sản phẩm',
                'slug' => 'san-pham',
                'description' => 'Sản phẩm',
                'is_visible' => true,
                'seo_title' => 'san-pham',
                'seo_description' => 'san-pham',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Bài viết',
                'slug' => 'bai-viet',
                'description' => 'Bài viết',
                'is_visible' => true,
                'seo_title' => 'bai-viet',
                'seo_description' => 'bai-viet',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Dự án',
                'slug' => 'du-an',
                'description' => 'Dự án',
                'is_visible' => true,
                'seo_title' => 'du-an',
                'seo_description' => 'du-an',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Liên hệ',
                'slug' => 'lien-he',
                'description' => 'Liên hệ',
                'is_visible' => true,
                'seo_title' => 'lien-he',
                'seo_description' => 'lien-he',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Đại lý',
                'slug' => 'dai-ly',
                'description' => 'Đại lý',
                'is_visible' => true,
                'seo_title' => 'dai-ly',
                'seo_description' => 'dai-ly',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Hỗ trợ',
                'slug' => 'ho-tro',
                'description' => 'Hỗ trợ',
                'is_visible' => true,
                'seo_title' => 'ho-tro',
                'seo_description' => 'ho-tro',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Tải về',
                'slug' => 'tai-ve',
                'description' => 'Tải về',
                'is_visible' => true,
                'seo_title' => 'tai-ve',
                'seo_description' => 'tai-ve',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Quy định và chính sách',
                'slug' => 'quy-dinh-va-chinh-sach',
                'description' => 'Quy định và chính sách của Phoenix',
                'is_visible' => true,
                'seo_title' => 'quy-dinh-va-chinh-sach',
                'seo_description' => 'quy-dinh-va-chinh-sach',
                'parent_id' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ]);

        $ProductCategory = Category::where('slug', 'san-pham')->first();
        DB::table('categories')->insert([
            [
                'name' => 'Line Array',
                'slug' => 'line-array',
                'description' => 'Line Array',
                'is_visible' => true,
                'seo_title' => 'line-array',
                'seo_description' => 'line-array',
                'parent_id' => $ProductCategory->id,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Loa / Speaker',
                'slug' => 'loa-speaker',
                'description' => 'Loa / Speaker',
                'is_visible' => true,
                'seo_title' => 'loa-speaker',
                'seo_description' => 'loa-speaker',
                'parent_id' => $ProductCategory->id,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Công suất / Amplifier',
                'slug' => 'cong-suat-amplifier',
                'description' => 'Công suất / Amplifier',
                'is_visible' => true,
                'seo_title' => 'cong-suat-amplifier',
                'seo_description' => 'cong-suat-amplifier',
                'parent_id' => $ProductCategory->id,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Microphone',
                'slug' => 'microphone',
                'description' => 'Microphone',
                'is_visible' => true,
                'seo_title' => 'microphone',
                'seo_description' => 'microphone',
                'parent_id' => $ProductCategory->id,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Vang / Mixer',
                'slug' => 'vang-mixer',
                'description' => 'Vang / Mixer',
                'is_visible' => true,
                'seo_title' => 'vang-mixer',
                'seo_description' => 'vang-mixer',
                'parent_id' => $ProductCategory->id,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Loa trầm / Sub',
                'slug' => 'loa-tram-sub',
                'description' => 'Loa trầm / Sub',
                'is_visible' => true,
                'seo_title' => 'loa-tram-sub',
                'seo_description' => 'loa-tram-sub',
                'parent_id' => $ProductCategory->id,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Quản lý nguồn điện',
                'slug' => 'quan-ly-nguon-dien',
                'description' => 'Quản lý nguồn điện',
                'is_visible' => true,
                'seo_title' => 'quan-ly-nguon-dien',
                'seo_description' => 'quan-ly-nguon-dien',
                'parent_id' => $ProductCategory->id,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Phụ kiện âm thanh',
                'slug' => 'phu-kien-am-thanh',
                'description' => 'Phụ kiện âm thanh',
                'is_visible' => true,
                'seo_title' => 'phu-kien-am-thanh',
                'seo_description' => 'phu-kien-am-thanh',
                'parent_id' => $ProductCategory->id,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'name' => 'Dàn loa Karaoke',
                'slug' => 'dan-loa-karaoke',
                'description' => 'Dàn loa Karaoke',
                'is_visible' => true,
                'seo_title' => 'dan-loa-karaoke',
                'seo_description' => 'dan-loa-karaoke',
                'parent_id' => $ProductCategory->id,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ]);
    }
}
